// Generated by tools/cast.py (the Casting plane).
plugins {
    id("mold.rust-gates") version "0.1.13"
    id("mold.comment-hygiene") version "0.1.13"
}

// The module-edge dependency guard has NO published plugin (the one gate that is
// project-authored): cast.py emits the task + matrix parser here. Fill in
// gradle/dependency-guard.config with your tier matrix; an illegal edge then fails
// `check` (-> build), not just a review. See casting-adoption.md.
tasks.register("dependencyGuard") {
    group = "verification"
    description = "Fails any project->project edge outside gradle/dependency-guard.config."
    val matrixFile = file("gradle/dependency-guard.config")
    val modules = subprojects
    doLast {
        val matrix = DependencyMatrix.parse(matrixFile.readText())
        val violations = modules.flatMap { module ->
            module.configurations
                .flatMap { it.dependencies }
                .filterIsInstance<ProjectDependency>()
                .map { it.path }
                .distinct()
                .filter { it != module.path }
                .filterNot { matrix.permits(module.path, it) }
                .map { "${module.path}  ->  $it" }
        }.distinct().sorted()
        if (violations.isNotEmpty()) {
            throw GradleException(
                "Dependency guard: ${violations.size} edge(s) outside the matrix:\n" +
                    violations.joinToString("\n") { "  $it" },
            )
        }
        logger.lifecycle("Dependency guard: ${modules.size} modules, every edge within the matrix.")
    }
}

subprojects {
    tasks.matching { it.name == "check" }.configureEach {
        dependsOn(rootProject.tasks.named("dependencyGuard"))
    }
}

// A contract target matches face-precise (contract:state); any other by bare tier.
class DependencyMatrix(private val allowed: Map<String, Set<String>>) {
    fun permits(source: String, target: String): Boolean {
        val targetSegments = target.split(":").filter { it.isNotEmpty() }
        val spec = if (targetSegments.firstOrNull() == "contract" && targetSegments.size >= 2) {
            "contract:${targetSegments[1]}"
        } else {
            targetSegments.firstOrNull().orEmpty()
        }
        return spec in (allowed[tierOf(source)] ?: emptySet())
    }

    private fun tierOf(path: String): String =
        path.split(":").firstOrNull { it.isNotEmpty() }.orEmpty()

    companion object {
        fun parse(text: String): DependencyMatrix {
            val allowed = text.lineSequence()
                .map { it.substringBefore('#').trim() }
                .filter { it.isNotEmpty() }
                .associate { line ->
                    require("->" in line) { "dependency-guard.config: rule has no '->': `$line`" }
                    val tier = line.substringBefore("->").trim()
                    val specs = line.substringAfter("->").trim()
                        .split(Regex("\\s+")).filter { it.isNotEmpty() }.toSet()
                    tier to specs
                }
            return DependencyMatrix(allowed)
        }
    }
}

// Cross-wire the cargo-root rust gates into each module's wall: the cargo root is a
// plain project, so rust-gates' in-plugin fold finds no local gatesFast/Full; this
// binding makes a broken crate fail the same wall (enforcement.md, ADR-0010).
subprojects {
    tasks.matching { it.name == "gatesFast" }
        .configureEach { dependsOn(rootProject.tasks.named("rustGatesFast")) }
    tasks.matching { it.name == "gatesFull" }
        .configureEach { dependsOn(rootProject.tasks.named("rustGatesFull")) }
}
