// Generated by tools/cast.py (the Casting plane). The law Maven repo is the FIRST
// pluginManagement repository so the mold.* plugins resolve before any other source.
pluginManagement {
    includeBuild("build-logic")
    repositories {
        maven { url = uri("file:///mnt/companion/president/maven-casting") }  // mold casting law repo
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "resetprop-rs"

// Add your tier graph here, e.g.:
// include(":app")
// include(":core:foo")
