// Generated by tools/cast.py. VERSION-PIN LOCATION #2 of 2: the convention jar so
// the project's convention plugins can apply mold.kotlin-quality and mold.gates by
// id. Keep in lockstep with the root build's pin (both == castingVersion).
plugins {
    `kotlin-dsl`
}

dependencies {
    // The mold casting law. The AGP/Kotlin gradlePlugin deps below let Gradle
    // generate the type-safe plugin accessors the convention plugins use.
    implementation("mold.casting:convention:0.1.13")
    // implementation(libs.android.gradlePlugin)
    // implementation(libs.kotlin.gradlePlugin)
}
