// Generated by tools/cast.py. build-logic is a standalone included build, so it
// does NOT inherit the root's repositories or version catalog: the law repo is wired
// here SECOND (miss it -> "Could not find mold.casting:convention"), and the same
// gradle/libs.versions.toml is imported by path so the catalog stays one SSOT.
dependencyResolutionManagement {
    repositories {
        maven { url = uri("file:///mnt/companion/president/maven-casting") }  // mold casting law repo
        gradlePluginPortal()
        google()
        mavenCentral()
    }
    versionCatalogs {
        create("libs") {
            from(files("../gradle/libs.versions.toml"))
        }
    }
}

rootProject.name = "build-logic"
